name: 'libriheavy download'
description: 'libriheavy download interactive'
tags: ['libriheavy download', 'interactive']
setup_command: 'bash setup.sh'
command: 'bash run.sh'
environment_variables:
  USE_BOLT_EXPERIMENTAL_CONDA: "1"
project_id: foundation_models
parameters:
  epochs: 100
resources:
  docker_image: 'docker.apple.com/zhipeng_han/gpt:cuda11.8.0-ubuntu20.04'
  num_cpus: 8
  memory_gb: 512
  ports: ['VIZ_PORT', 'NOTEBOOK_PORT', 'IR_PORT', 'IRMAN_PORT', 'TMP1_PORT', 'TMP2_PORT']
  num_gpus: 1
  disk_gb: 1024
  timeout: 14d
  cluster: 'kube_us_west_2b'
gpu_options:
  cuda_version: '11.2'
  cudnn_version: '8.1'
